# Generated by Django 3.1.2 on 2020-10-06 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_password', models.CharField(max_length=30)),
                ('employee_age', models.IntegerField()),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to='users/')),
            ],
        ),
    ]
